name: "Pull Request Labeler"
on:
  pull_request_target:
  workflow_dispatch:
    inputs:
      prs:
        required: false
        description: "pr number"

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          pr-number: github.event.inputs.prs
